/************************************************** 
 * Arquivo de log 
 * 
 * Data Criação: 25/02/2013 01:21 
 *************************************************/ 
——————————————————————- 
Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:21:21 
Erro [ 0 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 46 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Área Restrita. Login ou Senha inválidos 
Trace: 
{
0 C:\xampp\LGFramework\core\Pagina.php(60): core\Autenticador->verificarAcesso('todos', Array)

1 C:\xampp\LGFramework\core\Roteador.php(44): core\Pagina->verificarAcesso()

2 C:\xampp\htdocs\site\index.php(11): core\Roteador->verificarAcesso()

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:28:29 
Erro [ 0 ]: C:\xampp\LGFramework\core\Roteador.php linha ( 70 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Esta página não pode ser acessada. 
Trace: 
{
0 C:\xampp\htdocs\site\index.php(12): core\Roteador->chamarMetodo()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:48 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:50 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:50 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:51 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:51 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:51 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:51 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:51 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:51 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:52 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:52 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:52 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:52 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:52 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:37:52 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:42:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:42:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:33 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:33 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:34 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:34 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:34 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:34 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:34 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:34 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:35 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:35 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:55 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:55 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:56 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:56 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:56 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:56 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:56 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:43:56 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:44:14 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:44:14 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:04 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:04 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:04 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:28 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:28 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:28 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:29 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:30 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:30 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:30 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:45 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:45 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:45 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:45:45 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:07 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:07 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:08 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:08 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:08 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:08 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:08 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:08 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:47 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:47 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:48 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:48 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:48 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 01:46:48 
Erro [ 2 ]: C:\xampp\LGFramework\core\Autenticador.php linha ( 29 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed 
Trace: 
{
0 C:\xampp\LGFramework\system\erros.php(13): exceptions\PHPException::throwError(2, 'session_regener...', 'C:\xampp\LGFram...', 29)

1 [internal function]: handleError(2, 'session_regener...', 'C:\xampp\LGFram...', 29, Array)

2 C:\xampp\LGFramework\core\Autenticador.php(29): session_regenerate_id(true)

3 C:\xampp\LGFramework\core\Autenticador.php(23): core\Autenticador->renovarSessao()

4 C:\xampp\htdocs\site\controller\Login.php(8): core\Autenticador->__construct(Object(model\Usuario))

5 C:\xampp\LGFramework\core\Pagina.php(17): controller\Login->__construct()

6 C:\xampp\htdocs\site\controller\Usuario.php(8): core\Pagina->__construct(Object(model\Usuario))

7 C:\xampp\LGFramework\core\Roteador.php(28): controller\Usuario->__construct()

8 C:\xampp\htdocs\site\index.php(10): core\Roteador->instanciarController()

9 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 03:36:59 
Erro [ 0 ]: C:\xampp\LGFramework\system\erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'view\configuracoes' not found28C:\xampp\LGFramework\core\Roteador.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 03:38:15 
Erro [ 0 ]: C:\xampp\LGFramework\system\erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'view\Configuracoes' not found29C:\xampp\LGFramework\core\Roteador.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 03:38:43 
Erro [ 0 ]: C:\xampp\LGFramework\system\erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'view\m\Usuario' not found8C:\xampp\htdocs\site\view\Configuracoes.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 10:50:22 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'view/Configuracoes' not found29/var/www/projetos/LGFramework/core/Roteador.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 10:51:26 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 10:51:40 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:11:23 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:11:23 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:11:24 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:07 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:08 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:08 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:08 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:09 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:09 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:09 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'controller/Login' not found17/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 11:12:46 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5) failed: Permission denied (13)4/var/www/projetos/LGFramework/system/session_start.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:41:34 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 18 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 18)

1 /var/www/projetos/LGFramework/core/Roteador.php(18): handleError(8, 'Undefined offse...', '/var/www/projet...', 18, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:41:46 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 18 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 18)

1 /var/www/projetos/LGFramework/core/Roteador.php(18): handleError(8, 'Undefined offse...', '/var/www/projet...', 18, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:42:02 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 18 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 18)

1 /var/www/projetos/LGFramework/core/Roteador.php(18): handleError(8, 'Undefined offse...', '/var/www/projet...', 18, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:42:54 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 17 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined variable: action 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined varia...', '/var/www/projet...', 17)

1 /var/www/projetos/LGFramework/core/Roteador.php(17): handleError(8, 'Undefined varia...', '/var/www/projet...', 17, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:43:06 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 20 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 20)

1 /var/www/projetos/LGFramework/core/Roteador.php(20): handleError(8, 'Undefined offse...', '/var/www/projet...', 20, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:43:07 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 20 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 20)

1 /var/www/projetos/LGFramework/core/Roteador.php(20): handleError(8, 'Undefined offse...', '/var/www/projet...', 20, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:43:08 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 20 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 20)

1 /var/www/projetos/LGFramework/core/Roteador.php(20): handleError(8, 'Undefined offse...', '/var/www/projet...', 20, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:43:08 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 20 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 20)

1 /var/www/projetos/LGFramework/core/Roteador.php(20): handleError(8, 'Undefined offse...', '/var/www/projet...', 20, Array)

2 /var/www/projetos/ge/html/index.php(9): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:44:08 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 39 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined index: controller 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined index...', '/var/www/projet...', 39)

1 /var/www/projetos/LGFramework/core/Autenticador.php(39): handleError(8, 'Undefined index...', '/var/www/projet...', 39, Array)

2 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso(Array, 'todos')

3 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

4 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

5 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:45:33 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 39 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Use of undefined constant CONTROLLER_PAGINA_LOGIN - assumed 'CONTROLLER_PAGINA_LOGIN' 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Use of undefine...', '/var/www/projet...', 39)

1 /var/www/projetos/LGFramework/core/Autenticador.php(39): handleError(8, 'Use of undefine...', '/var/www/projet...', 39, Array)

2 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso(Array, 'todos')

3 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

4 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

5 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:45:48 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 39 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined index: method 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined index...', '/var/www/projet...', 39)

1 /var/www/projetos/LGFramework/core/Autenticador.php(39): handleError(8, 'Undefined index...', '/var/www/projet...', 39, Array)

2 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso(Array, 'todos')

3 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

4 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

5 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:46:11 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 42 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined index: method 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined index...', '/var/www/projet...', 42)

1 /var/www/projetos/LGFramework/core/Autenticador.php(42): handleError(8, 'Undefined index...', '/var/www/projet...', 42, Array)

2 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso(Array, 'todos')

3 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

4 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

5 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:46:11 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 42 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined index: method 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined index...', '/var/www/projet...', 42)

1 /var/www/projetos/LGFramework/core/Autenticador.php(42): handleError(8, 'Undefined index...', '/var/www/projet...', 42, Array)

2 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso(Array, 'todos')

3 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

4 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

5 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:46:11 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 42 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined index: method 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined index...', '/var/www/projet...', 42)

1 /var/www/projetos/LGFramework/core/Autenticador.php(42): handleError(8, 'Undefined index...', '/var/www/projet...', 42, Array)

2 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso(Array, 'todos')

3 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

4 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

5 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:46:12 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 42 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined index: method 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined index...', '/var/www/projet...', 42)

1 /var/www/projetos/LGFramework/core/Autenticador.php(42): handleError(8, 'Undefined index...', '/var/www/projet...', 42, Array)

2 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso(Array, 'todos')

3 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

4 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

5 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 16:46:17 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Call to undefined method controller\Usuario::addGeneralContent()37/var/www/projetos/ge/html/controller/Usuario.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:09:04 
Erro [ 0 ]: /var/www/projetos/LGFramework/core/Autenticador.php linha ( 46 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Área Restrita. Login ou Senha inválidos 
Trace: 
{
0 /var/www/projetos/LGFramework/core/Controller.php(31): core\Autenticador->verificarAcesso('todos', Array)

1 /var/www/projetos/LGFramework/core/Roteador.php(59): core\Controller->verificarAcesso()

2 /var/www/projetos/ge/html/index.php(11): core\Roteador->verificarAcesso()

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:11:14 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'core\exceptions\AcessException' not found46/var/www/projetos/LGFramework/core/Autenticador.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:15:00 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath15/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:15:01 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath15/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:15:04 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath15/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:15:04 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath15/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:15:16 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath15/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:15:54 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath16/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:16:16 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath17/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:17:08 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath14/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:17:09 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath14/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:54:42 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath14/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 17:54:43 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Undefined variable: fullpath14/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:20:59 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Use of undefined constant APP_PATH - assumed 'APP_PATH'10/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:21:21 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Use of undefined constant APP_PATH - assumed 'APP_PATH'10/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:21:43 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Use of undefined constant APP_PATH - assumed 'APP_PATH'10/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:21:59 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Use of undefined constant APP_PATH - assumed 'APP_PATH'10/var/www/projetos/LGFramework/system/paths.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:22:32 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'view\Login' not found43/var/www/projetos/LGFramework/core/Roteador.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:22:41 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'view\Login' not found43/var/www/projetos/LGFramework/core/Roteador.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:27:28 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 22 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 22)

1 /var/www/projetos/LGFramework/core/Roteador.php(22): handleError(8, 'Undefined offse...', '/var/www/projet...', 22, Array)

2 /var/www/projetos/ge/html/index.php(10): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:29:13 
Erro [ 8 ]: /var/www/projetos/LGFramework/core/Roteador.php linha ( 22 ) 
Mensagem Usuário:Erro Geral 
Mensagem Interna:Undefined offset: 0 
Trace: 
{
0 /var/www/projetos/LGFramework/system/erros.php(13): exceptions\PHPException::throwError(8, 'Undefined offse...', '/var/www/projet...', 22)

1 /var/www/projetos/LGFramework/core/Roteador.php(22): handleError(8, 'Undefined offse...', '/var/www/projet...', 22, Array)

2 /var/www/projetos/ge/html/index.php(10): core\Roteador->__construct('c')

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:30:59 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'view\Login' not found45/var/www/projetos/LGFramework/core/Roteador.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:31:31 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:syntax error, unexpected $end, expecting T_FUNCTION24/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:31:44 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login20/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:32:11 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Class 'core\Exception' not found48/var/www/projetos/LGFramework/core/Pagina.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:33:02 
Erro [ 1002 ]: /var/www/projetos/LGFramework/core/Pagina.php linha ( 48 ) 
Mensagem Usuário:Ocorreu um erro no site. Entre em contato com o suporte. 
Mensagem Interna:O Template login.tpl não existe 
Trace: 
{
0 /var/www/projetos/ge/html/view/Login.php(21): core\Pagina->setTemplate('login.tpl')

1 /var/www/projetos/LGFramework/core/Roteador.php(81): view\Login->login('wXJlYSBSZXN0cml...')

2 /var/www/projetos/ge/html/index.php(13): core\Roteador->chamarMetodo()

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:33:02 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login20/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:33:30 
Erro [ 1002 ]: /var/www/projetos/LGFramework/core/Pagina.php linha ( 48 ) 
Mensagem Usuário:Ocorreu um erro no site. Entre em contato com o suporte. 
Mensagem Interna:O Template login.tpl não existe 
Trace: 
{
0 /var/www/projetos/ge/html/view/Login.php(20): core\Pagina->setTemplate('login.tpl')

1 /var/www/projetos/LGFramework/core/Roteador.php(81): view\Login->login('wXJlYSBSZXN0cml...')

2 /var/www/projetos/ge/html/index.php(13): core\Roteador->chamarMetodo()

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:33:30 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:33:31 
Erro [ 1002 ]: /var/www/projetos/LGFramework/core/Pagina.php linha ( 48 ) 
Mensagem Usuário:Ocorreu um erro no site. Entre em contato com o suporte. 
Mensagem Interna:O Template login.tpl não existe 
Trace: 
{
0 /var/www/projetos/ge/html/view/Login.php(20): core\Pagina->setTemplate('login.tpl')

1 /var/www/projetos/LGFramework/core/Roteador.php(81): view\Login->login('wXJlYSBSZXN0cml...')

2 /var/www/projetos/ge/html/index.php(13): core\Roteador->chamarMetodo()

3 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:33:31 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:34:16 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:37:52 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:39:20 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

Classe: exceptions\ExceptionHandler Usuario: 
Hora: 25/02/2013 - 18:39:37 
Erro [ 0 ]: /var/www/projetos/LGFramework/system/erros.php linha ( 20 ) 
Mensagem Usuário:Ocorreu um problema 
Mensagem Interna:Redefining already defined constructor for class view\Login19/var/www/projetos/ge/html/view/Login.php 
Trace: 
{
0 [internal function]: handleShutdown()

1 {main}} 
——————————————————————- 

